Zgłoszenie rozwiązania
ShouldIStayOrShouldIGo/pio_git_rhymers pull request #9
Opened 2020-01-06 20:56 UTC by ShouldIStayOrShouldIGo

2020-01-08 09:25 UTC, kowallus requested changes
A crucial part of lab. is missing. See 1.4 and "Temat: stałe i annotacje"
Review hints: tiny.cc/2rkvgz

2020-01-08 09:25 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/FIFORhymer.java
> +public final class FIFORhymer extends DefaultCountingOutRhymer {
There was no task concerning class modifiers

2020-01-08 09:25 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/list/IntLinkedList.java
> +    private int i;
Unused private field could be removed.

2020-01-08 09:25 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/list/Node.java
> +    private int value;
Immutable - should be final (setter unnecessary)

2020-01-13 15:40 UTC, ShouldIStayOrShouldIGo commented
Files have been changed. Corrections in commented files

2020-01-21 12:27 UTC, merged

2020-01-21 12:27 UTC, kowallus commented
-0.5 pts